GET http://localhost:3000/ HTTP/1.1
###
GET http://localhost:3000/v1/users HTTP/1.1
###
POST http://localhost:3000/v1/register HTTP/1.1
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"test1"
}
###
POST http://localhost:3000/v1/login HTTP/1.1
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"test1"
}
###
GET http://localhost:3000/v1/articles HTTP/1.1
###
POST http://localhost:3000/v1/articles HTTP/1.1
Content-Type: application/json

{
    "date": "2000-09-12",
    "title": "Something about css",
    "content": "This is a perfect article to read and learn more about css"
}
###